# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('createdby', models.IntegerField(verbose_name='CREATEDBY')),
                ('custid', models.IntegerField(verbose_name='CUSTID')),
                ('ITEMNUM', models.CharField(max_length=40)),
                ('DESCRIPTION', models.CharField(max_length=110)),
                ('lead', models.IntegerField(verbose_name='LEAD')),
                ('hours', models.IntegerField(verbose_name='HOURS')),
                ('datedue', models.DateField(verbose_name='DATEDUE')),
                ('cdate', models.DateField(verbose_name='CDATE')),
                ('COMMENT', models.CharField(max_length=255)),
                ('ecr', models.BooleanField(verbose_name='ECR')),
                ('ecrid', models.IntegerField(verbose_name='ECRID')),
                ('new', models.BooleanField(verbose_name='NEW')),
            ],
        ),
    ]
